### ISSUE TITLE
Manage Contractor => Contractor accept/reject reason doesn't persist. 

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#107]
When approve/reject a contractor with reason, the reason doesn't persist.

**Comment by tungpham** [comment]
Yup data is saved and read back. However, there's no notification when any operation is completed?

**Comment by Darko-Vasilev** [comment]
fixed

**Comment by tungpham** [comment]
Good, I see it now. 

There's an issue with our app right now is that all notifications appear in the bottom left of the screen. Can you make all notifications appear on top, center of the screen?

**Comment by Darko-Vasilev** [comment]
fixed
