### ISSUE TITLE
Project Detail layout

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#110]
I think for UI consistency, the project detail layout should be the same layout as Add New Project, or Edit Project. In the readonly view, make the field name in bold.

**Comment by Darko-Vasilev** [comment]
fixed. want feedback

**Comment by tungpham** [comment]
Look a lot better. 

Due date is an important attribute, so swap its position with the Status. 

Make Contractor Information narrower. Also display other attributes of the contractor (name, address, etc...)

**Comment by Darko-Vasilev** [comment]
fixed
