### ISSUE TITLE
Capture input when new project is created

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#118]
Input are dimensions of a house. Make it dynamic so user can:

- Add a level
- Each level, user can add 1 or more rooms
- For each room, user can specify 3 dimensions (width/length/height)

**Comment by tungpham** [comment]
- a level can have more than 1 bedroom, more than 1 bathroom, so you should not take out the option on the dropdown menu.
- Let's include a "description" field for each room (besides the dimension)
- Rearrange the dimension fields (w/l/h) to be close together. Maybe like this (2 columns table, 1st column has 3 rows for the 2 dimensions, 2nd column just 1 row for the description)

w: 3 | Description:
l:  3  | blablabla
h: 3  |

**Comment by cubu** [comment]
Also, please allow user to access Level information after they submit the project. Currently, after we submit it, we have no way to view and make changes.
