### ISSUE TITLE
Contractor Detail - When clicking on Past Project or Photos/Videos, the Slider width/height should be 80% and 70%

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#130]
When clicking on Past Project or Photos/Videos, the Slider width/height should be 80% and 70% of screen size respectively, while keeping the image original ratio (ie. image will be scaled up to fit the slider, but original ratio remain the same so that the picture is not distorted). Right now I think you get the width correct, but not the height.

**Comment by karanpujara** [comment]
> When clicking on Past Project or Photos/Videos, the Slider width/height should be 80% and 70% of screen size respectively, while keeping the image original ratio (ie. image will be scaled up to fit the slider, but original ratio remain the same so that the picture is not distorted). Right now I think you get the width correct, but not the height.

It's been Complete, Check it Once.

**Comment by tungpham** [comment]
http://localhost:4000/contractordetails/b579a3de-8e01-4668-b80c-7c1a40068f69 

Past project picture: 

![Screen Shot 2019-11-08 at 10 47 57 PM](https://user-images.githubusercontent.com/2773056/69909303-de267e00-13be-11ea-9f1e-68c1a19d73f4.png)

When click on it, the picture is cut off

![Screen Shot 2019-11-30 at 10 15 23 PM](https://user-images.githubusercontent.com/2773056/69909304-f26a7b00-13be-11ea-9eba-26b23c7c5592.png)

**Comment by karanpujara** [comment]
It has been done. Check it once.

**Comment by karanpujara** [comment]
It has been done. Check it once.

**Comment by tungpham** [comment]
Nope. Let me use a concrete example. Here's the original image that user upload for a Past project. Notice the ratio

![Screen Shot 2019-11-08 at 10 47 57 PM](https://user-images.githubusercontent.com/2773056/70494439-ed997b80-1ad0-11ea-991b-967e39f286d6.png)

Here's should be the image when that Past project is clicked on from Contractor profile page (Search -> search result -> Contractor profile)

![Screen Shot 2019-12-09 at 8 15 02 PM](https://user-images.githubusercontent.com/2773056/70494497-1d488380-1ad1-11ea-819d-dd57a224bef9.png)

Here, the image is scaled up in size, but maintain its original ratio. 

What we currently have, the image is scaled up, but the ratio is distorted. Not to mention the back/next arrow now sits on top of the image, which it should NOT. 

![Screen Shot 2019-12-09 at 10 15 38 PM](https://user-images.githubusercontent.com/2773056/70494605-84663800-1ad1-11ea-99e5-f478e8e3f825.png)

**Comment by tungpham** [comment]
@karanpujara I see a lot of error in the console, and the slider Photos/Videos is having issue. Items should have some padding between them. Also, it should only have 6 items (4 pictures, 2 videos). The type TWITTER should be the hyperlink under the Social Media section

![Screen Shot 2019-12-11 at 12 02 52 AM](https://user-images.githubusercontent.com/2773056/70595842-fad66900-1ba9-11ea-908f-0b7f467c5c1e.png)

**Comment by karanpujara** [comment]
Its been done.
