### ISSUE TITLE
Make avatar display be of square size (NxN). Right now it's retangular

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#131]
Search result and contractor detail pages

**Comment by tungpham** [comment]
@karanpujara Why is the logo not vertically aligned with the rest of the text? I think it should move left a little to align vertically
![Screen Shot 2019-11-27 at 11 06 03 PM](https://user-images.githubusercontent.com/2773056/69778617-98717780-116a-11ea-8253-dcf96394f1d7.png)

**Comment by karanpujara** [comment]
It's been Complete, Check it Once.
