### ISSUE TITLE
Restyle General Contractor table

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#134]
Refer to Req #1

**Comment by karanpujara** [comment]
1. There is no data for New tab in General Contractor.
2. There is no data for Ongoing tab in General Contractor.
3. There is data for Completed/Archived tab but in data there are some columns data are missing like Contractor, Location, Start Date , End Date.

API : -  https://bcbe-service.herokuapp.com/contractors/b579a3de-8e01-4668-b80c-7c1a40068f69/projects?status=ARCHIVED

**Comment by tungpham** [comment]
API updated to include missing fields. Note that the returned list of projects now has the project details inside the "project" element

By default, status is ACTIVE 
https://bcbe-service.herokuapp.com/contractors/b579a3de-8e01-4668-b80c-7c1a40068f69/projects

https://bcbe-service.herokuapp.com/contractors/b579a3de-8e01-4668-b80c-7c1a40068f69/projects?status=ONGOING

https://bcbe-service.herokuapp.com/contractors/b579a3de-8e01-4668-b80c-7c1a40068f69/projects?status=ARCHIVED

**Comment by karanpujara** [comment]
In General Contractor on Ongoing tab there are three icons(RED, GREEN & YELLOW) so, in last column  PROJECT DETAILS which shows based on condition and there is no data fetching from API related to particular condition so how can we set icons on basis of which field of contion.(Please refer INVSION wireframe (GENERAL CONTRACTOR)

**Comment by karanpujara** [comment]
In all table there are fields of date like Upload date , Start date , End date etc which are contains HH:MM:SS AM in INVISION APP so we have to put that HH:MM:SS AM like invision app or we need to display time ?

**Comment by karanpujara** [comment]
In all table there are fields of date like Upload date, Start date, End date etc which are contains HH:MM:SS AM in INVISION APP so we have to put that HH:MM:SS AM like invision app or we need to display time ?

**Comment by tungpham** [comment]
> In General Contractor on Ongoing tab there are three icons(RED, GREEN & YELLOW) so, in last column PROJECT DETAILS which shows based on condition and there is no data fetching from API related to particular condition so how can we set icons on basis of which field of contion.(Please refer INVSION wireframe (GENERAL CONTRACTOR)

Please treat them the same as Project description in NEW

**Comment by tungpham** [comment]
> In all table there are fields of date like Upload date, Start date, End date etc which are contains HH:MM:SS AM in INVISION APP so we have to put that HH:MM:SS AM like invision app or we need to display time ?

How are you going to display time different than what in the invision?

**Comment by karanpujara** [comment]
> How are you going to display time different than what in the invision?

I meant that I am only getting 'Date' not getting 'time' from API and in Invision it's mentioned so, for now, I am just displaying 00:00:00 in time. Check-in general contractor getting 'startDate: "2019-03-11" add time in API.

**Comment by karanpujara** [comment]
> How are you going to display time different than what in the invision?

I meant that I am only getting 'Date' not getting 'time' from API and in Invision it's mentioned so, for now, I am just displaying 00:00:00 in time. Check-in general contractor getting 'startDate: "2019-03-11" add time in API.

**Comment by tungpham** [comment]
> > How are you going to display time different than what in the invision?
> 
> I meant that I am only getting 'Date' not getting 'time' from API and in Invision it's mentioned so, for now, I am just displaying 00:00:00 in time. Check-in general contractor getting 'startDate: "2019-03-11" add time in API.

@karanpujara The backend is updated with date field that has time information. Field "submittedDate" should be displayed on General Contractor -> New -> Uploaded date. Same goes for Start Date and End date on "Ongoing"

**Comment by tungpham** [comment]
@karanpujara Please fix the wide gap 
![Screen Shot 2019-11-25 at 5 44 04 PM](https://user-images.githubusercontent.com/2773056/69779340-50078900-116d-11ea-9e81-7e483ff98091.png)

**Comment by tungpham** [comment]
@karanpujara table pagination is broken

**Comment by tungpham** [comment]
@karanpujara Please move the Bids, Location, Budget, Upload Date, Bids Due columns closer together. The data for these columns are small in nature. That way there's more space for Project Details

**Comment by tungpham** [comment]
@karanpujara The sorting on columns is not working?

**Comment by karanpujara** [comment]
> @karanpujara The backend is updated with date field that has time information. Field "submittedDate" should be displayed on General Contractor -> New -> Uploaded date. Same goes for Start Date and End date on "Ongoing"

Are you sure that I need to display submitted date field in both start & end date on OnGoing Tab, because in End Date, we need to find difference between two days so how is it possible with same dates?

**Comment by karanpujara** [comment]
> @karanpujara The sorting on columns is not working?

Can you add more data so that I can Check weather column Sorting is working or not excluding GenContractor -> NEW Tab.

**Comment by karanpujara** [comment]
> @karanpujara table pagination is broken. Select 10, the forward/backward arrow not working

Here is the Same, Need to add More data(at least 10-15) So, I can test the Pagination feature in other tabs excluding GenContrator -> NEW Tab. The Changes has been made for New Tab.

**Comment by tungpham** [comment]
> > @karanpujara table pagination is broken. Select 10, the forward/backward arrow not working
> 
> Here is the Same, Need to add More data(at least 10-15) So, I can test the Pagination feature in other tabs excluding GenContrator -> NEW Tab. The Changes has been made for New Tab.

??? There are 156 projects for contractor test4@bc.com, why do we need more? It's broken because you're calling it incorrectly. It's apparent from the Console https://bcbe-service.herokuapp.com/contractors/b579a3de-8e01-4668-b80c-7c1a40068f69/projects?page=[object%20Object]&size=20

**Comment by tungpham** [comment]
> > @karanpujara The sorting on columns is not working?
> 
> Can you add more data so that I can Check whether column Sorting is working or not excluding GenContractor -> NEW Tab. The Changes has been made for New Tab.

Bid due column seems to sort, but not Upload date. Make sure they're working

**Comment by tungpham** [comment]
> > @karanpujara The backend is updated with date field that has time information. Field "submittedDate" should be displayed on General Contractor -> New -> Uploaded date. Same goes for Start Date and End date on "Ongoing"
> 
> Are you sure that I need to display submitted date field in both start & end date on OnGoing Tab, because in End Date, we need to find difference between two days so how is it possible with same dates?

I'm talking about the NEW tab, why are you talking about Ongoing? There's no submitted date in Ongoing.

**Comment by tungpham** [comment]
> > > @karanpujara table pagination is broken. Select 10, the forward/backward arrow not working
> > 
> > 
> > Here is the Same, Need to add More data(at least 10-15) So, I can test the Pagination feature in other tabs excluding GenContrator -> NEW Tab. The Changes has been made for New Tab.
> 
> ??? There are 156 projects for contractor [test4@bc.com](mailto:test4@bc.com), why do we need more? It's broken because you're calling it incorrectly. It's apparent from the Console [https://bcbe-service.herokuapp.com/contractors/b579a3de-8e01-4668-b80c-7c1a40068f69/projects?page=[object%20Object]&size=20](https://bcbe-service.herokuapp.com/contractors/b579a3de-8e01-4668-b80c-7c1a40068f69/projects?page=%5Bobject%20Object%5D&size=20)

@karanpujara Page size footer should be fixed. Baseline: 

![Screen Shot 2019-12-03 at 3 53 49 PM](https://user-images.githubusercontent.com/2773056/70093847-e5c86b80-15e6-11ea-912a-b70eb131b0a0.png)

Currently, the spacing doesn't look right. There should be some spacing between the number and the drop down. Also, the page "moved/resized" when the dropdown is clicked.
![pagesizedropdown](https://user-images.githubusercontent.com/2773056/70094170-8c147100-15e7-11ea-9903-fc4f12b68634.gif)

**Comment by tungpham** [comment]
@karanpujara The space between the static band (search) and the table is too large. 

![Screen Shot 2019-12-05 at 10 41 47 PM](https://user-images.githubusercontent.com/2773056/70297399-7e134b80-17b3-11ea-9f6c-9e20602ebb83.png)

This space for the Sub Contractor tab is too small

![Screen Shot 2019-12-05 at 10 42 18 PM](https://user-images.githubusercontent.com/2773056/70297445-b1ee7100-17b3-11ea-8d33-f5ab61a69630.png)

Also, this gap is inconsistent between the Submitted tab and Awarded tab

![Screen Shot 2019-12-05 at 10 42 18 PM](https://user-images.githubusercontent.com/2773056/70297474-cfbbd600-17b3-11ea-86d3-cf9c030537cb.png)

Please adjust them so they're consistent, and look like the design.

**Comment by karanpujara** [comment]
It is done, Check it once.

**Comment by karanpujara** [comment]
It is done, Check it Once.
