### ISSUE TITLE
Restyle Sub Con view

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#135]
Req #2

**Comment by tungpham** [comment]
Note: You can skip the Bids column in Submitted.
In Awarded/Completed, Owner columns is the project.genContractor.address.name field

**Comment by karanpujara** [comment]
1. There is no data for Awarded Tab in sub Contractor.
        
API:-https://bcbe-service.herokuapp.com/projects/b579a3de-8e01-4668-b80c-7c1a40068f69/proposals?status=AWARDED

2. There is no data for Completed Tab in Sub Contractor.

API:-https://bcbe-service.herokuapp.com/projects/b579a3de-8e01-4668-b80c-7c1a40068f69/proposals?status=INACTIVE

**Comment by karanpujara** [comment]
In Sub Contractor on Awarded tab there are three icons(RED, GREEN & YELLOW) so, in last column  PROJECT DETAILS which shows based on condition and there is no data fetching from API related to particular condition so how can we set icons on basis of which field of contion.(Please refer INVSION wireframe (SUB CONTRACTOR)

**Comment by tungpham** [comment]
> In Sub Contractor on Awarded tab there are three icons(RED, GREEN & YELLOW) so, in last column PROJECT DETAILS which shows based on condition and there is no data fetching from API related to particular condition so how can we set icons on basis of which field of contion.(Please refer INVSION wireframe (SUB CONTRACTOR)

You're right, it's more like project status. Please disregard that and just display Project description, similar to Submitted

**Comment by tungpham** [comment]
@karanpujara Need fix on the wide gap on the menu bar 
![Screen Shot 2019-11-25 at 5 46 24 PM](https://user-images.githubusercontent.com/2773056/69779098-74169a80-116c-11ea-8329-4a83b495e594.png)

**Comment by tungpham** [comment]
@karanpujara Remove the shadow on this, and please make it fixed size. Otherwise, when viewing on a laptop screen, it look nice. However, on desktop, this menu is too wide
![Screen Shot 2019-11-27 at 11 23 17 PM](https://user-images.githubusercontent.com/2773056/69779266-061ea300-116d-11ea-9db8-513e68c77a11.png)

**Comment by tungpham** [comment]
@karanpujara Please move Bids|Location|Price|Upload Date|Bids Due columns closer together so there're more spaces for Project Details

**Comment by tungpham** [comment]
@karanpujara Now the Search box disappear. 

"Submited" is misspelled. 

Also, related to #139, make that section (Submitted | Awarded | Completed and the search box) static (not moving), similar to the baseline http://bcfe0.s3-website.us-east-2.amazonaws.com/s_cont/pipeline/submitted. You should do the same for the General Contractor  as well where the search box and the Add project button remain static. Only the table content scroll.

**Comment by mansijoshi17** [comment]
it has been done. Check it Once.

**Comment by karanpujara** [comment]
It has been done. Check it once.
