### ISSUE TITLE
Redo vertical side menu and top navbar per design

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#136]
Req #3

**Comment by tungpham** [comment]
@karanpujara from the design, note that the vertical side menu should overlay the main page

**Comment by tungpham** [comment]
@karanpujara notice from the design, the vertical side menu is complete below the navbar

**Comment by tungpham** [comment]
@karanpujara The side menu should be open/close on mouse hover anywhere on the menu itself. Right now it only open/close when mouse is hover over the menu items, and not when the mouse is on the area below it

**Comment by karanpujara** [comment]
> @karanpujara The side menu should be open/close on mouse hover anywhere on the menu itself. Right now it only open/close when mouse is hover over the menu items, and not when the mouse is on the area below it

It's been Complete, Check it Once.
