### ISSUE TITLE
New Project modal series integration 

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#137]
Req #4

**Comment by karanpujara** [comment]
Getting issue in Post API (Genereal Contractor ADD Project Modal series). Just go through this video.
https://drive.google.com/file/d/1JKaor1_tLf8se2_VNA8u9psGxkB65pSV/view?usp=sharing

**Comment by tungpham** [comment]
> Getting issue in Post API (Genereal Contractor ADD Project Modal series). Just go through this video.
> https://drive.google.com/file/d/1JKaor1_tLf8se2_VNA8u9psGxkB65pSV/view?usp=sharing

I watched the video and not sure what the issue is? Not all information from the modal series is captured for now. As long as you include them in the request, once the backend is ready, those info will be captured

**Comment by tungpham** [comment]
@karanpujara on the POST new project, please remove the genContractor, submittedDate, projectFiles, projectInvites, projectSpecialites, projectTemplates, year, id fields from the request body.

budget: null
city: "Ha Noi"
description: "fdf dfd fdfdfdfdfdf fljdfldkfjdfdf dfdsf dsf dfsa fdsfd fdfdf dfdf df dfd fdf df df df"
due: null
duration: null
endDate: "2019-12-05T05:33:52.537Z"
genContractor: {id: "b579a3de-8e01-4668-b80c-7c1a40068f69", email: "test4@bc.com", status: "ACTIVE",…}
id: "96655378-75c8-4cfe-a404-f702a66a51be"
projectFiles: null
projectInvites: null
projectSpecialties: null
projectTemplates: null
relationships: null
startDate: "2019-03-11 13:10:10"
status: "ACTIVE"
submittedDate: null
title: "A project"
type: "OWNER_PROJECT"
year: null

**Comment by karanpujara** [comment]
I think this will be covered by backend developer right?

**Comment by tungpham** [comment]
@karanpujara it doesn't affect anything. It's just a matter of not sending useless information on the request

**Comment by karanpujara** [comment]
@tungpham I am just sending 1) Title 2) Budget 3) Description and 4) Due date. As we are not passing below four fields,  its being taken as NULL by backend and that's why it returns NULL in response.
projectFiles: null
projectInvites: null
projectSpecialties: null
projectTemplates: null
relationships: null

**Comment by karanpujara** [comment]
@tungpham In "Budget" section of Add project modal, when I am passing string value "Less than 12000" from radio button then it is taking null | 0. Maybe because I am passing string and from backend its taken Number type. I cant pass number because its range so need to send data in String. Can you please look into this?

**Comment by tungpham** [comment]
> @tungpham I am just sending 1) Title 2) Budget 3) Description and 4) Due date. As we are not passing below four fields, its being taken as NULL by backend and that's why it returns NULL in response.
> projectFiles: null
> projectInvites: null
> projectSpecialties: null
> projectTemplates: null
> relationships: null

Yup that's fine. These fields are null for now

**Comment by tungpham** [comment]
> @tungpham In "Budget" section of Add project modal, when I am passing string value "Less than 12000" from radio button then it is taking null | 0. Maybe because I am passing string and from backend its taken Number type. I cant pass number because its range so need to send data in String. Can you please look into this?

Can you put 'budget' to be the upper value, and add fields 'budgetFrom', 'budgetTo' corresponding to the range values

**Comment by karanpujara** [comment]
@tungpham Wanted to confirm that do I need to send the data in the following format:
budget: ""
budgetFrom: "$50000"
budgetTo: "$100000"
description: "$50000-$100000$50000-$100000$50000-$100000$50000-$100000"
due: "2019-12-11T07:08:13.801Z"
title: "A project"

**Comment by tungpham** [comment]
@karanpujara description is from the last modal screen (anything you want to tell us ) right?

**Comment by karanpujara** [comment]
@tungpham Ignore "description" field. Its my mistake I copied range in description by mistake. Finally I am sending budgetFrom: 50000 budgetTo: 10000 (as a number not string) please pass this to backend developer.
