### ISSUE TITLE
Production build looks different than local build

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#138]

**Comment by tungpham** [comment]
@karanpujara side menu on production build moves on hover

![sidemenu](https://user-images.githubusercontent.com/2773056/70189604-5a6bda80-16b9-11ea-99c1-73afb27a535f.gif)

**Comment by karanpujara** [comment]
It's done, Check it once. Here is the video link 
 https://drive.google.com/file/d/1P1pxYtjxFvSA2P8A0qyOw-Y9oSGgpLy8/view?usp=sharing   
go through it.

**Comment by karanpujara** [comment]
Issues resolved, Here is the video link
https://drive.google.com/file/d/1ZXD1_D51lulfDzyd6ckEhLQzVO15T4Oj/view?usp=sharing
 go through it.
