### ISSUE TITLE
Remove Footer section from the rest of the pages

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#139]
Footer section should be on the home page only. Putting the Footer section on all other page breaks the natural flow of the page, ie. scrolling of the content, and scrolling of the page itself. Now we have 2 scrollbars.

**Comment by karanpujara** [comment]
> Footer section should be on the home page only. Putting the Footer section on all other page breaks the natural flow of the page, ie. scrolling of the content, and scrolling of the page itself. Now we have 2 scrollbars.

It's been Complete, Check it Once.

**Comment by tungpham** [comment]
@karanpujara You need to fix the 2 scrollbar issue. Before, there's only 1 scrollbar on the page. Please refer to http://bcfe0.s3-website.us-east-2.amazonaws.com. Notice how there's always 1 scrollbar on the page.

Now, there are 2 scrollbars, which make the page look ugly

**Comment by tungpham** [comment]
@karanpujara still need to fix the layout so that the Tabs bar doesn't move. It should be static on the page. Here's the baseline vs. what's being done now

![baseline](https://user-images.githubusercontent.com/2773056/70093633-7488b880-15e6-11ea-82df-6e5a49b8fac0.gif)
![tobefixed](https://user-images.githubusercontent.com/2773056/70093645-7bafc680-15e6-11ea-85e9-d03015f9bb66.gif)

**Comment by mansijoshi17** [comment]
it has been done. Check it Once.

**Comment by karanpujara** [comment]
It has been done. Check it once.

**Comment by tungpham** [comment]
1. As stated from the beginning, the footer should only be removed from other pages except for the home page. Right now it's removed from the home page.

2. On General Contractor tab, there's hidden footer. Why is it there? It should be removed. Make sure it's removed for Ongoing and Completed as well

![Screen Shot 2019-12-09 at 9 40 08 PM](https://user-images.githubusercontent.com/2773056/70493363-07d15a80-1acd-11ea-89a8-e0fa0d4c44cd.png)
