### ISSUE TITLE
Sub Contractor -> Awarded -> click on project -> wrong URL called

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#142]
404 in console. This is a regression issue. The URL when clicking on the project should be https://bcbe-service.herokuapp.com/proposals/0b1fddc4-350c-47d5-89e0-e0acc9f5616c/temCatOptionDetail
![Screen Shot 2019-11-30 at 11 24 50 PM](https://user-images.githubusercontent.com/2773056/69909950-b50aeb00-13c8-11ea-835f-ac2d0fd74de5.png)

**Comment by mansijoshi17** [comment]
it has been done. Check it Once.

**Comment by karanpujara** [comment]
It has been done. Check it once.
