### ISSUE TITLE
Contractor Detail - Photos/Videos - incorrect file type filtering 

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#151]
http://bcfe.s3-website.us-east-2.amazonaws.com/contractordetails/b579a3de-8e01-4668-b80c-7c1a40068f69

{{host}}/contractors/b579a3de-8e01-4668-b80c-7c1a40068f69 returns 
....
    "contractorFiles": [
        {
            "id": "fb2f169b-2245-4380-adb1-2977f1b73859",
            "name": "Screen Shot 2019-11-08 at 10.47.57 PM.png",
            "type": "PICTURE",
            "note": "photo+2"
        },
        {
            "id": "c8cb3f10-f507-4725-a71b-a53bdc116075",
            "name": "Screen Shot 2019-12-02 at 11.29.03 PM.png",
            "type": "PICTURE",
            "note": "photo+4"
        },
        {
            "id": "1c99488e-e3b3-4f9e-8fae-311330b44141",
            "name": "Screen Shot 2019-11-07 at 6.10.01 PM.png",
            "type": "DOCUMENT",
            "note": "Ha noi__Construction license__323293832"
        },
        {
            "id": "7633966c-3938-44d9-b9e9-f14d2ff07bf2",
            "name": "https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DsHsFIv8VA7w",
            "type": "LINK",
            "note": "a+youtube+link"
        },
        {
            "id": "b22c3c28-198f-406e-8c84-ddae5eabdb65",
            "name": "Screen Shot 2019-11-25 at 5.44.04 PM.png",
            "type": "PICTURE",
            "note": "photo+3"
        },
        {
            "id": "fe048454-dccb-4831-8413-25cf34233e26",
            "name": "https%3A%2F%2Ftwitter.com%2FSkySportsPL",
            "type": "TWITTER",
            "note": null
        },
        {
            "id": "7c685c93-5977-4a47-aea4-c65c58106054",
            "name": "Screen Shot 2019-12-07 at 11.30.50 PM.png",
            "type": "PICTURE",
            "note": "photo+1"
        }
    ],

for Photos, it should filter out item with type "PICTURE" only. For Videos, it should filter out items of type "LINK" only. Therefore, for this contractor, Photos and Videos section only has 5 items. Right now it also count the Document and TWITTER into this section, thus resulting in NOT FOUND item on this section Photos and Videos.

To get the detail picture, there's 2 methods:
by id: https://bcbe-service.herokuapp.com/swagger-ui.html#/contractor-controller/getContractorFileByFileIdUsingGET (notice the id is a query paramter)

and the current method:
https://bcbe-service.herokuapp.com/swagger-ui.html#/contractor-controller/getContractorFileByFileNameUsingGET

**Comment by karanpujara** [comment]
@tungpham In type LINK for video, I am getting https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DsHsFIv8VA7w. idle link should be youtube.com/'embed'/'videoid'  so can I get proper embed link for video? or is there any specific FORMAT you guys are following to form a video link out of above URL?

**Comment by karanpujara** [comment]
@tungpham Also, please resolve this so I can test full project. Getting Error in Profile page. go through the link http://bcfe0.s3-website.us-east-2.amazonaws.com/profile

**Comment by tungpham** [comment]
> @tungpham In type LINK for video, I am getting https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DsHsFIv8VA7w. idle link should be youtube.com/'embed'/'videoid' so can I get proper embed link for video? or is there any specific FORMAT you guys are following to form a video link out of above URL?

The code should already convert the regular link https://www.youtube.com/watch?v=XXXXX to the embedded version. There's probably some bug somewhere in the code that broke to parse that link. I removed that link and added 2 others, and it should work now

**Comment by tungpham** [comment]
> @tungpham Also, please resolve this so I can test full project. Getting Error in Profile page. go through the link http://bcfe0.s3-website.us-east-2.amazonaws.com/profile

it should work now

**Comment by tungpham** [comment]
@karanpujara In the Photos and Videos section, the note on each photo/video is eclipsed by the lower picture. You should add more vertical padding/spacing so that it is clearly visible. You can see it in the baseline

![Screen Shot 2019-12-10 at 11 58 47 PM](https://user-images.githubusercontent.com/2773056/70595504-24db5b80-1ba9-11ea-853a-c8901a293e1e.png)

**Comment by tungpham** [comment]
@karanpujara there should be 4 photos only (4 photos + 2 videos), not 8

![Screen Shot 2019-12-11 at 10 37 52 PM](https://user-images.githubusercontent.com/2773056/70683196-fcb23200-1c66-11ea-804c-cd19153af3c5.png)

**Comment by karanpujara** [comment]
It has been done. check it Once.
