### ISSUE TITLE
Contractor Profile (User Profile) - picture/video notes got eclipsed

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#153]
Should add more vertical padding between items? 

![Screen Shot 2019-12-10 at 11 58 47 PM](https://user-images.githubusercontent.com/2773056/70597880-1e4fe280-1baf-11ea-999b-09e118108156.png)

**Comment by tungpham** [comment]
@karanpujara 

![Screen Shot 2019-12-11 at 10 11 54 PM](https://user-images.githubusercontent.com/2773056/70682784-94af1c00-1c65-11ea-9ccb-d6890e48b4f3.png)

This is when I click on Past Project in User Profile (to edit it, etc..)

- The warning on the console. What i don't get is why it doesn't happen in the baseline, assuming they're all separate?

- As you can see, the line "Location" is not aligned with "Service", it's a little bit above "Service". Also, the size of the modal is a lot smaller compared to the baseline. Why is the style on this page got overwritten by what you're changing?

**Comment by karanpujara** [comment]
Its been done.

**Comment by tungpham** [comment]
> Its been done.

I'm still seeing the warning about wrong way of coding in the console?

**Comment by tungpham** [comment]
@karanpujara whatever css change was made, it now distort the home page? the field City is now unaligned

<img width="644" alt="Screen Shot 2019-12-13 at 9 25 36 PM" src="https://user-images.githubusercontent.com/2773056/70842927-85f47080-1def-11ea-87e4-c957908a49e9.png">

Also, the Location line on the User Profile Past Project is still not 100% align, i think it's 2-3 pixel uneven. Same thing for the lines below it (project title, duration, year, etc..). Are you fixing it by manually adjusting the position and not have the layout manager manage it?

**Comment by tungpham** [comment]
> @karanpujara
> 
> ![Screen Shot 2019-12-11 at 10 11 54 PM](https://user-images.githubusercontent.com/2773056/70682784-94af1c00-1c65-11ea-9ccb-d6890e48b4f3.png)
> 
> This is when I click on Past Project in User Profile (to edit it, etc..)
> 
> * The warning on the console. What i don't get is why it doesn't happen in the baseline, assuming they're all separate?
> * As you can see, the line "Location" is not aligned with "Service", it's a little bit above "Service". Also, the size of the modal is a lot smaller compared to the baseline. Why is the style on this page got overwritten by what you're changing?

@karanpujara did you look at the issue above? "It has been done"....on the latest change i still the same issue

Also, please put back the setting on the .env when you commit, otherwise it's breaking the deployment to prod, https://github.com/tungpham/bcfe/blob/master/.env#L7

Also put back the setting to prevent youtube player from auto play https://github.com/tungpham/bcfe/blob/master/src/containers/ProfileView/ProfilePhotos.tsx#L255

**Comment by karanpujara** [comment]
> Why did you remove eslint? https://github.com/tungpham/bcfe/blob/master/src/components/BeforeLogin/ContractorDetails.js#L1

@tungpham I didn't remove any ESLint script.

**Comment by karanpujara** [comment]
![Screen Shot 2019-12-16 at 6 48 42 PM](https://user-images.githubusercontent.com/3678906/70910151-2687a200-2035-11ea-9694-8b921a115da4.png)
@tungpham It's fixed now. Please, check it.

**Comment by tungpham** [comment]
> > Why did you remove eslint? https://github.com/tungpham/bcfe/blob/master/src/components/BeforeLogin/ContractorDetails.js#L1
> 
> @tungpham I didn't remove any ESLint script.

@karanpujara This commit https://github.com/tungpham/bcfe/commit/81ddf9ca67e2eda53d67a608cc7c2beeb1b7a32b#diff-e4ca29a1bcd36dc86a1141ead3831c2b the line wasn't there. The subsequent commit introduced that line, eslint-disable

**Comment by karanpujara** [comment]
> > > Why did you remove eslint? https://github.com/tungpham/bcfe/blob/master/src/components/BeforeLogin/ContractorDetails.js#L1
> > 
> > 
> > @tungpham I didn't remove any ESLint script.
> 
> @karanpujara This commit [81ddf9c#diff-e4ca29a1bcd36dc86a1141ead3831c2b](https://github.com/tungpham/bcfe/commit/81ddf9ca67e2eda53d67a608cc7c2beeb1b7a32b#diff-e4ca29a1bcd36dc86a1141ead3831c2b) the line wasn't there. The subsequent commit introduced that line, eslint-disable

@tungpham I have tested the code and made sure it's as per Eslint guidelines but later I noticed it ESLint is disabled in your theme so I added that in my code.
Here I have enabled it in my code and made sure there are no console warnings/errors please have a check.
