### ISSUE TITLE
User Profile -> Ask for Review -> Send Request did not call backend

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#154]
@karanpujara SEND REQUEST should call POST {{host}}/contractors/{{con_id}}/request_reviews (ie. https://bcbe-service.herokuapp.com/contractors/b579a3de-8e01-4668-b80c-7c1a40068f69/request_reviews), with request payload (not json, it's just an array of the emails entered on the modal) ["fdfdsf@fjdlf.com"]

Regression from the baseline http://bcfe0.s3-website.us-east-2.amazonaws.com/profile. Not to mention the text on Email preview is smaller than what it was before

**Comment by mansijoshi17** [comment]
![ProfileReviewSection](https://user-images.githubusercontent.com/54347081/71234091-b2dbe280-231d-11ea-8145-9e8b1be1108a.png)
@tungpham The same response I m getting from the http://bcfe0.s3-website.us-east-2.amazonaws.com/profile.I have not changed this code POST request is already made for "Send Request" button.

**Comment by karanpujara** [comment]
![ProfileReviewSection](https://user-images.githubusercontent.com/3678906/71237342-47970e00-2327-11ea-9935-da49868b41dc.png)
@tungpham  The same response I'm getting from the http://bcfe0.s3-website.us-east-2.amazonaws.com/profile. I have not made any changes in POST request for the "ASK FOR REVIEW" button.
