### ISSUE TITLE
Write Review should retrieve contractor information from api

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#161]
- {{host}}/reviews/{{con_id}}/write

here {{con_id}} is the contractor id, you use this id to retrieve the information about this contractor by calling {{host}}/contractors/{{con_id}}. This will give you the contractor name, etc...Right now the value "Super cleaner" is hard coded. And note that {{host}} here is our site host url, not the backend service url

- The contractor avatar is retrieved using {{host}}/contractors/{{con_id}}/avatar

- "By clicking Submit you agree to ~~use~~ Terms of Use and Privacy Policy" should be "By clicking Submit you agree to Terms of Use and Privacy Policy" 

- Also reduce the font size for "By clicking Submit you agree to Terms of Use and Privacy Policy"

- On submit, POST to {{host}}/reviews/{{con_id}}/write

**Comment by IkramDev25** [comment]
Hello
I have fixed
![image](https://user-images.githubusercontent.com/54520718/71514384-4a6ea180-28d9-11ea-8418-24ebe6f2d978.png)

at this moment, api is not working on backend side
