### ISSUE TITLE
Login -> Profile failed

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#175]
Logged out. Then Sign in. Got this warning

![Screen Shot 2019-12-30 at 10 44 15 PM](https://user-images.githubusercontent.com/2773056/71610393-2ec3ff00-2b56-11ea-8f33-1bcd2c2d1b48.png)

It still signed in. Then click on avatar => Profile. The app crash

![Screen Shot 2019-12-30 at 10 44 53 PM](https://user-images.githubusercontent.com/2773056/71610400-3edbde80-2b56-11ea-8853-998f20ba0557.png)

**Comment by IkramDev25** [comment]
Hi Tim
How are you?

I am going to ask one thing to you.
Can we discuss about that in Skype?
Thanks
Ikram
