### ISSUE TITLE
Create some visual Hierarchy for "Template -> Category -> Option"

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#28]
Because we switching among Template/Category/Option tab, there should be some visual indicator showing where we're at, ie. if i'm in Option 3, of Category 2, of Template 1, then I should see something like "Template 1 -> Category 2 -> Option 3" to indicate where I am right now.

One way is to create a breadcrumb and insert it between the tabs and the display table (ideal). Otherwise, in Category detail, you can put the parent Template name (in bold font, readonly, optionally make it a link so when I click on it, it take me back to the Template Detail) above the Category name. Same for Option, on the Option Detail, we can put Template Name, Category name (in bold, readonly) ABOVE the Option name.

**Comment by tungpham** [comment]
Make them vertical stacked, and left align

**Comment by 3DMLAB** [comment]
Tungpham, Arghhh...Discord crash.  Please use new server: SETE Connect#6567 or email me at protonmail. Best -- PJ
