### ISSUE TITLE
Subcontractor => Submitted => ... => Proposal Detail click Back to All Proposals should return to the previously selected tab 

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#39]
Subcontractor => Submitted => ... => Proposal Detail click Back to All Proposals should return to the previously selected tab. Right now, when I click back, it always return to Won tab.

**Comment by tungpham** [comment]
This bug is related to the separation between Submitted proposal and Awarded proposal. Right now, all proposals are in Submitted tab. Need to separate them

**Comment by ikatugin** [comment]
I do pagination from the information returning from api. 
To do filtering and pagination, I need filtered data from api.
