### ISSUE TITLE
compare view should have radio selection for each option, as describe in requirement doc

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#44]
Different selection will result in different Template total, and Project total as a whole

**Comment by Darko-Vasilev** [comment]
fixed

**Comment by tungpham** [comment]
can you put the radio button on its own column, so that the Subtotal line is in the same column as the option

<img width="584" alt="Screen Shot 2019-06-05 at 8 06 36 PM" src="https://user-images.githubusercontent.com/2773056/58999871-a2bf4400-87cd-11e9-8a33-974005fd0c77.png">

**Comment by tungpham** [comment]
We also need the Project total, which is the sum of all the Sub Total (Template total)

**Comment by Darko-Vasilev** [comment]
Project total already exists. template total were fixed
