### ISSUE TITLE
Option Editing page. vertical line issue

### ISSUE THREAD

**Issue by Darko-Vasilev** [tungpham/bcfe#47]
You should also implement the grid system to be similar to Manage Templates where the vertical divider is resizable.

**Comment by tungpham** [comment]
<img width="581" alt="Screen Shot 2019-06-05 at 8 55 54 PM" src="https://user-images.githubusercontent.com/2773056/59001490-5f1c0880-87d4-11e9-8d57-800afdd5b9d4.png">

**Comment by tungpham** [comment]
Another example
![Screen Shot 2019-06-05 at 9 47 43 PM](https://user-images.githubusercontent.com/2773056/59003445-9a6e0580-87db-11e9-8f08-d43ff9ffd132.png)

**Comment by tungpham** [comment]
You should put some spacing within the grid to make the vertical lines separate from each other a bit

**Comment by Darko-Vasilev** [comment]
fixed

**Comment by tungpham** [comment]
What about my comments above?
