### ISSUE TITLE
implement Refresh button on All Items view to refresh All Items table only instead of the whole page

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#49]

**Comment by karanpujara** [comment]
Tom refresh button is only updating table of Items views instead of whole page. For your reference please check this video:
https://drive.google.com/file/d/1rqHI9-v85_yTygQlWTiWSNvHi8PLyOEd/view?usp=sharing

**Comment by tungpham** [comment]
@karanpujara this is out of scope.
