### ISSUE TITLE
Add Project rearrangement

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#53]
Make Add Project form left-align. 
**Title**: _________________________________
**Price**: _______________________________
**Description**: 
(an editor text area)

Make the Add file be a button. We need the space for future attribute of project

**Comment by Darko-Vasilev** [comment]
fixed. want some feedback

**Comment by tungpham** [comment]
Can you make the form all the way to the left. I don't want it to be constrained. Just make the form be the whole page. 

Price can just be a regular input field. Take out the arrow up/down at the end

**Comment by Darko-Vasilev** [comment]
fixed
