### ISSUE TITLE
SubContractor => Submitted delete proposal doesn't refresh the page

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#55]
- Clicking on delete proposal in Submitted, the deleted proposal doesn't get removed from the page.

- Click on a proposal to the Proposal Detail view, click on Delete Proposal, failed to delete because proposal_id is not sent on the request

![Screen Shot 2019-06-08 at 1 43 46 PM](https://user-images.githubusercontent.com/2773056/59151143-9ae0e900-89f3-11e9-8e31-aa026eddbe1a.png)

**Comment by Darko-Vasilev** [comment]
fixed
