### ISSUE TITLE
Display project owner info (gen contractor) on Projects => Project Detail => Overview

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#56]
- Make this look nicely. Besides project information, display some information about the project owner as well (General Contractor info from GET /project)

Title: _______________________________           Posted Date:_______________
Budget:
Description:
(text area)

Location: (no data for now)

=======
General Contractor:
Email:
Name:
Address:

- Change the tab order in Project Detail as: Overview | Files | Templates | Proposals | Bidders. Remove the Message tab

**Comment by Darko-Vasilev** [comment]
fixed

**Comment by tungpham** [comment]
You need change the tab order as well (see description)

**Comment by tungpham** [comment]
Also, can you remove the File list on the Overview tab. We already have the Files tab, no need to display the list of files on the Overview tab
