### ISSUE TITLE
Put back Message tab in Proposal Detail view

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#61]
**Current:**

![Screen Shot 2019-06-08 at 12 37 49 PM](https://user-images.githubusercontent.com/2773056/59150498-484eff00-89ea-11e9-8ff6-bf370fb3c481.png)

**It was: (the message tab was there will all the message)**

![Screen Shot 2019-06-08 at 12 38 27 PM](https://user-images.githubusercontent.com/2773056/59150505-5ac93880-89ea-11e9-8fd5-9a523575c411.png)

![Screen Shot 2019-06-08 at 12 46 09 PM](https://user-images.githubusercontent.com/2773056/59150594-84cf2a80-89eb-11e9-899a-998266ed332e.png)

**Refer to this commit **08bb00b66db1dcb7a9031c792c7d7ff04d2c4fe3****

**Comment by Darko-Vasilev** [comment]
fixed
