### ISSUE TITLE
Enhance Proposal Detail View | Message to periodically poll for new message in the background every 30 second

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#62]
- Poll for new message every 30 sec
- Color code user email and the other person email on each message

![Screen Shot 2019-06-08 at 12 46 09 PM](https://user-images.githubusercontent.com/2773056/59150585-754fe180-89eb-11e9-8de2-850eb114158d.png)

**Comment by karanpujara** [comment]
> * Poll for new message every 30 sec
> * Color code user email and the other person email on each message
> 
> ![Screen Shot 2019-06-08 at 12 46 09 PM](https://user-images.githubusercontent.com/2773056/59150585-754fe180-89eb-11e9-8de2-850eb114158d.png)

Sorry I didn't get your point. Can you please give more details for this?

**Comment by tungpham** [comment]
@karanpujara this is not in your scope, only issues with your name.
