### ISSUE TITLE
Update General Contractor => Project Detail => Proposals => Proposal Detail View => Detail tab

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#63]
- Remove the Project Info section. Replace with the info from the Proposal itself.
- Include information about the Sub Contractor as well
- Remove the table Project Template. Replace it with just a bullet list of templates, like this:

Templates:
- tem1
- tem2

![Screen Shot 2019-06-08 at 3 56 56 PM](https://user-images.githubusercontent.com/2773056/59152260-1d72a400-8a06-11e9-979c-1b38c0ea91eb.png)

**Comment by Darko-Vasilev** [comment]
modified

**Comment by tungpham** [comment]
Proposal info is the main information. Put proposal info first, then sub contractor info. Leave enough area/space for Proposal description. In the future we'll put in an Editor component for the description.

**Comment by Darko-Vasilev** [comment]
fixed

**Comment by tungpham** [comment]
Like I said, the Proposal info is the important information, why do we still display it as "disabled" look and feel? As you can see, it's gray out. Can you make it like normal? 

Also, we should make all the header uniform (Proposal Information/Sub Contractor Information/Template). Right now, this page look kinda messy :)

![Screen Shot 2019-06-11 at 11 22 22 PM](https://user-images.githubusercontent.com/2773056/59323324-d1db2700-8c9f-11e9-81a9-5a7bf67cce33.png)
