### ISSUE TITLE
Create "Archived" tab in General Contractor tab

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#64]
- Create "Archive" tab in General Contractor tab, next to "Add Project"
- When gen contractor hit the Delete icon on project (in Current Projects tab), move the project to Archive tab.

Update Delete action to PUT /projects/{project_id}/archive

To populate Archive tab, call GET /contractors/{gen_id}/projects?status=ARCHIVED

**Comment by Darko-Vasilev** [comment]
fixed

**Comment by tungpham** [comment]
When I delete the project, it error out
![Screen Shot 2019-07-04 at 2 36 20 PM](https://user-images.githubusercontent.com/2773056/60685538-3b96bd00-9e69-11e9-9062-91eef01ce625.png)

**Comment by Darko-Vasilev** [comment]
fixed

**Comment by tungpham** [comment]
I just tested it and now it's a different error
<img width="954" alt="Screen Shot 2019-07-04 at 11 54 53 PM" src="https://user-images.githubusercontent.com/2773056/60698912-42e4b780-9eb7-11e9-9f3a-a190aa3ea20e.png">

**Comment by Darko-Vasilev** [comment]
Please check again.

**Comment by tungpham** [comment]
![Untitled](https://user-images.githubusercontent.com/2773056/60745176-b4b41400-9f3e-11e9-96cd-c5216bc23456.gif)
