### ISSUE TITLE
Display user email next to the avatar icon on the top right corner

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#65]
![Screen Shot 2019-06-09 at 2 54 38 PM](https://user-images.githubusercontent.com/2773056/59163412-8d486380-8ac6-11e9-93fb-d2078d790adf.png)

**Comment by Darko-Vasilev** [comment]
fixed.

**Comment by tungpham** [comment]
We want the actual email value displayed, not the email icon :)

**Comment by Darko-Vasilev** [comment]
fixed
