### ISSUE TITLE
Shrink the size of table header, header font size in Proposal compare view

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#67]
Can we shrink the font size of the table header, and the header row itself? They're too big now, and if the template has lot of categories, this will be very big

![Screen Shot 2019-06-12 at 12 02 18 AM](https://user-images.githubusercontent.com/2773056/59324669-8b88c680-8ca5-11e9-9a77-6ba762eec62f.png)

**Comment by Darko-Vasilev** [comment]
fixed. 24px->20px, size: medium->small

**Comment by Darko-Vasilev** [comment]
fixed

**Comment by tungpham** [comment]
push? I don't see any change
