### ISSUE TITLE
Make the table fill the entire area

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#79]
Let's make all the table fill the entire area, like before.

Before: (desired)

![Screen Shot 2019-06-27 at 11 31 43 PM](https://user-images.githubusercontent.com/2773056/60317246-c6d8f580-9933-11e9-8e44-59d7957b3867.png)

Now:

![Screen Shot 2019-06-27 at 11 32 14 PM](https://user-images.githubusercontent.com/2773056/60317258-d2c4b780-9933-11e9-8e0f-b8b19c7a3d7e.png)

**Comment by nhulongctk35** [comment]
Fixed.
