### ISSUE TITLE
Project due date

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#87]
A project has a due date for proposal submission. Currently this field, due date, is not displayed and stored.

Store: in add project, display a date picker for due date submission. Make this field next to the Price field. (Currently the price field takes the entire row. It should be a small input field).

Display: display the project due date in a any projects table. 

The due date field is called "due" in json request/response.

**Comment by Darko-Vasilev** [comment]
fixed

**Comment by tungpham** [comment]
Due date is not displayed in Projects => Project detail Overview.
